# Generated by Django 3.2.5 on 2021-08-01 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_job_creationdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='creationdate',
        ),
    ]
